# Generated by Django 2.0.8 on 2018-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180909_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ministatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('abalance', models.IntegerField(default=0)),
                ('tdate', models.CharField(max_length=30)),
            ],
        ),
    ]
